### ISSUE TITLE
Bij meerkoloms layout

### ISSUE THREAD

**Issue by Theo-denBlanken** [Pisav/responsiveGrid#3]
Je hebt feedback gekregen van **Theo-denBlanken**
URL: https://github.com/Pisav/responsiveGrid/blob/master/

Feedback: kunnen aside en footer makkelijk naast elkaar[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"reviewer":"Theo-denBlanken"}')

**Comment by Theo-denBlanken** [comment]
nog niet gedaan

**Comment by Pisav** [comment]
de aside staat nu goed

**Comment by Theo-denBlanken** [comment]
Ik zie ze nog steeds onder elkaar staan
